name: Check Agreement Lines

on: [push, pull_request]

jobs:
  check-files:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Check and Discard 'I Agree'
      run: |
        #!/bin/bash

        for file in "${FILES_TO_CHECK[@]}"; do
          # Check if the file ends with 'I agree' (case insensitive)
          if tail -n 1 "$file" | grep -Eiq "I agree$"; then
            echo "'I agree' found in $file, discarding changes..."
            # Reset the file to the last commit state
            git checkout -- "$file"
          else
            echo "'I agree' not found in $file"
          fi
        done
